const DEFAULT_KPI_MANAGER_ADDRESS = '0xCa82F1d0BBA127F4cC3A8881ea5991275A9E8Db5'; // New deployment Nov 24, 2025

export const CONTRACT_CONFIG = {
  KPI_MANAGER_ADDRESS: import.meta.env.VITE_KPI_CONTRACT_ADDRESS || DEFAULT_KPI_MANAGER_ADDRESS,
};

export const getKpiContractAddress = () => CONTRACT_CONFIG.KPI_MANAGER_ADDRESS;

